#include <Servo.h>

int _ABVAR_2_left_range_reading;
Servo servo_pin_11;
int _ABVAR_5_rspeed;
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  int duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(20);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  return duration;
}

int _ABVAR_3_right_range_reading;
int _ABVAR_1_front_range_reading;
int _ABVAR_4_lspeed;

void stop();
void left_range();
void right_range();
void rmotor_forward();
void scan();
void front_range();
void lmotor_forward();

void setup()
{
servo_pin_11.attach(11);
_ABVAR_2_left_range_reading = 0;
pinMode( 10 , OUTPUT);
_ABVAR_3_right_range_reading = 0;
_ABVAR_5_rspeed = 0;
_ABVAR_1_front_range_reading = 0;
digitalWrite( 7 , LOW );

pinMode( 9 , OUTPUT);
_ABVAR_4_lspeed = 0;
pinMode( 6 , OUTPUT);
pinMode( 5 , OUTPUT);
}

void loop()
{
front_range();
if (( ( _ABVAR_1_front_range_reading ) < ( 50 ) ))
{
scan();
if (( ( ( _ABVAR_2_left_range_reading ) > ( _ABVAR_3_right_range_reading ) ) || ( ( _ABVAR_2_left_range_reading ) > ( _ABVAR_1_front_range_reading ) ) ))
{
_ABVAR_4_lspeed = 200 ;
}
if (( ( ( _ABVAR_3_right_range_reading ) > ( _ABVAR_2_left_range_reading ) ) || ( ( _ABVAR_3_right_range_reading ) > ( _ABVAR_1_front_range_reading ) ) ))
{
_ABVAR_5_rspeed = 200 ;
}
}
else
{
_ABVAR_4_lspeed = 255 ;
_ABVAR_5_rspeed = 255 ;
}
lmotor_forward();
rmotor_forward();
}

void stop()
{
analogWrite(9 , 0);
analogWrite(10 , 0);
analogWrite(5 , 0);
analogWrite(6 , 0);
}

void right_range()
{
servo_pin_11.write( 45 );
delay( 300 );
_ABVAR_3_right_range_reading = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 7 , 8 ) ;
}

void lmotor_forward()
{
analogWrite(9 , _ABVAR_4_lspeed);
analogWrite(10 , 0);
}

void front_range()
{
servo_pin_11.write( 90 );
delay( 300 );
_ABVAR_1_front_range_reading = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 7 , 8 ) ;
}

void left_range()
{
servo_pin_11.write( 135 );
delay( 300 );
_ABVAR_2_left_range_reading = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 7 , 8 ) ;
}

void scan()
{
stop();
left_range();
front_range();
right_range();
}

void rmotor_forward()
{
analogWrite(5 , 0);
analogWrite(6 , _ABVAR_5_rspeed);
}


