int _ABVAR_3_rspeed;
int _ABVAR_1_sonar_range;
int _ABVAR_2_lspeed;
int _ABVAR_4_right_range;
int _ABVAR_5_front_range;
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  int duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(20);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  return duration;
}

int _ABVAR_6_left_range;

void read_sonar();
void rmotor_forward();
void stop();
void sonar_reset();
void lmotor_backward();
void spin_left();
void spin_Right();
void scan();
void lmotor_forward();
void rmotor_backward();

void setup()
{
digitalWrite( 7 , LOW );

Serial.begin(9600);
_ABVAR_6_left_range = 0;
pinMode( 12 , OUTPUT);
_ABVAR_1_sonar_range = 0;
_ABVAR_3_rspeed = 0;
pinMode( 6 , OUTPUT);
_ABVAR_2_lspeed = 0;
pinMode( 10 , OUTPUT);
pinMode( 13 , OUTPUT);
_ABVAR_4_right_range = 0;
pinMode( 9 , OUTPUT);
_ABVAR_5_front_range = 0;
pinMode( 5 , OUTPUT);
}

void loop()
{
read_sonar();
while ( ( ( _ABVAR_1_sonar_range ) < ( 40 ) ) )
{
read_sonar();
digitalWrite( 13 , HIGH );
_ABVAR_2_lspeed = 128 ;
_ABVAR_3_rspeed = 128 ;
spin_Right();
}

digitalWrite( 13 , LOW );
_ABVAR_2_lspeed = 255 ;
_ABVAR_3_rspeed = 255 ;
lmotor_forward();
rmotor_forward();
}

void lmotor_forward()
{
analogWrite(9 , _ABVAR_2_lspeed);
digitalWrite( 10 , LOW );
}

void read_sonar()
{
digitalWrite( 12 , LOW );
_ABVAR_1_sonar_range = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 7 , 8 ) ;
if (( ( _ABVAR_1_sonar_range ) <= ( 0 ) ))
{
_ABVAR_1_sonar_range = 999 ;
}
delay( 50 );
Serial.print( "Range:" );
Serial.print( _ABVAR_1_sonar_range );
Serial.println("");
}

void scan()
{
spin_Right();
_ABVAR_4_right_range = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 7 , 8 ) ;
delay( 1000 );
spin_left();
_ABVAR_5_front_range = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 7 , 8 ) ;
delay( 1000 );
spin_left();
_ABVAR_6_left_range = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 7 , 8 ) ;
delay( 1000 );
}

void stop()
{
digitalWrite( 9 , LOW );
digitalWrite( 10 , LOW );
digitalWrite( 5 , LOW );
digitalWrite( 6 , LOW );
}

void rmotor_forward()
{
analogWrite(6 , _ABVAR_2_lspeed);
digitalWrite( 5 , LOW );
}

void spin_left()
{
rmotor_forward();
lmotor_backward();
delay( 500 );
}

void sonar_reset()
{
digitalWrite( 12 , HIGH );
delay( 50 );
digitalWrite( 12 , LOW );
Serial.print( "Sonar RESET!" );
Serial.println("");
}

void lmotor_backward()
{
analogWrite(10 , _ABVAR_2_lspeed);
digitalWrite( 9 , LOW );
}

void spin_Right()
{
lmotor_forward();
rmotor_backward();
delay( 100 );
}

void rmotor_backward()
{
analogWrite(5 , _ABVAR_2_lspeed);
digitalWrite( 6 , LOW );
}


